import { Space, Artist, Booking } from '@/types'

export const sampleSpaces: Space[] = [
  {
    id: '1',
    name: '녹음실 A - 프리미엄',
    type: 'recording',
    description: '최고급 장비를 갖춘 프리미엄 녹음실입니다. K-POP 아티스트들의 앨범 레코딩에 최적화된 공간으로, 방음 시설과 최신 디지털 오디오 워크스테이션을 완비하고 있습니다.',
    equipment: ['Neumann U87', 'SSL Console', 'Pro Tools HDX', 'Genelec 8351B', 'Universal Audio Apollo x16', 'Avalon VT-737'],
    hourly_rate: 150000,
    capacity: 6,
    photos: [
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800',
      'https://images.unsplash.com/photo-1519508234439-4f23643a7e50?w=800',
    ],
    address: '서울시 강남구 역삼동 123-45',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: '녹음실 B - 스탠다드',
    type: 'recording',
    description: '보컬 녹음에 특화된 스탠다드 녹음실입니다. 가성비 좋은 장비 구성으로 데모 녹음부터 본격적인 레코딩까지 가능합니다.',
    equipment: ['AKG C414', 'Focusrite Clarett', 'Logic Pro X', 'Yamaha HS8', 'dbx 286s'],
    hourly_rate: 80000,
    capacity: 4,
    photos: [
      'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800',
    ],
    address: '서울시 마포구 합정동 67-89',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: '연습실 A - 대형',
    type: 'practice',
    description: '대형 그룹 연습에 적합한 넓은 연습실입니다. 전면 거울벽, 고급 음향 시스템, 우드 플로어를 갖추고 있어 안무 연습에 최적입니다.',
    equipment: ['JBL EON615 x4', '전면 거울벽', '우드 플로어', 'LED 조명', '에어컨'],
    hourly_rate: 60000,
    capacity: 15,
    photos: [
      'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=800',
    ],
    address: '서울시 성동구 성수동 456-78',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: '스튜디오 C - 복합',
    type: 'both',
    description: '녹음과 연습을 동시에 할 수 있는 복합 스튜디오입니다. 녹음 부스와 연습 공간이 분리되어 있어 효율적인 작업이 가능합니다.',
    equipment: ['Shure SM7B', 'Ableton Live', 'QSC K12.2 x2', '거울벽', '방음 부스', 'MIDI 키보드'],
    hourly_rate: 120000,
    capacity: 10,
    photos: [
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800',
    ],
    address: '서울시 용산구 이태원동 321-54',
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const sampleArtists: Artist[] = [
  {
    id: '1',
    user_id: null,
    name: 'NOVA',
    agency: 'Star Entertainment',
    genre: 'K-POP / 댄스',
    member_count: 5,
    bio: '2024년 데뷔한 5인조 보이그룹입니다. 파워풀한 퍼포먼스와 감성적인 보컬이 특징입니다.',
    profile_photo: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: null,
    name: 'LUNA',
    agency: 'Dream Music',
    genre: 'K-POP / R&B',
    member_count: 1,
    bio: '독보적인 음색과 작사 능력을 겸비한 솔로 아티스트입니다. R&B 기반의 K-POP을 선보이고 있습니다.',
    profile_photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: null,
    name: 'PRISM',
    agency: 'Bright Agency',
    genre: 'K-POP / 힙합',
    member_count: 4,
    bio: '힙합 기반의 음악을 하는 4인조 걸그룹입니다. 자체 작곡과 프로듀싱으로 주목받고 있습니다.',
    profile_photo: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400',
    created_at: new Date().toISOString(),
  },
]

export const sampleBookings: Booking[] = [
  {
    id: '1',
    space_id: '1',
    artist_id: '1',
    user_id: null,
    start_time: new Date(Date.now() + 86400000).toISOString(),
    end_time: new Date(Date.now() + 86400000 + 10800000).toISOString(),
    status: 'confirmed',
    total_price: 450000,
    notes: '앨범 레코딩 - 타이틀곡',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    space_id: '3',
    artist_id: '3',
    user_id: null,
    start_time: new Date(Date.now() + 172800000).toISOString(),
    end_time: new Date(Date.now() + 172800000 + 7200000).toISOString(),
    status: 'pending',
    total_price: 120000,
    notes: '안무 연습',
    created_at: new Date().toISOString(),
  },
]
